### ISSUE TITLE
Feedback on Tweet Gen

### ISSUE THREAD

**Issue by fchikwekwe** [PhraxayaM/CS-1.2-How-Data-Structures-Work#1]
Good work so far. I can see that you're definitely getting better at algorithm construction every time I look at your code. There are still few issues in this repo that you need to fix. 

Your stochastic sampling file is a little bit hard to read. It has weird spacing. Your final output doesn't have much to do with sampling by frequency. It calls a random words function instead. 

There are print statements within this file. I'm assuming that these were to try and test for relative probabilities, but again they just print the random words output.

**Comment by PhraxayaM** [comment]
Hi Faith,

Thank you for the feedback! I have made updates and we should be good to go.
