### ISSUE TITLE
Feedback for Linked Lists

### ISSUE THREAD

**Issue by fchikwekwe** [PhraxayaM/CS-1.2-How-Data-Structures-Work#2]
Great work with getting all your Linked Lists methods working! 

You had good commenting on some of your methods. I would suggest that you go back and clean up unnecessary spacing and bad formatting. 

I would **highly** recommend that you go back and do the Big O notation time complexity analysis for all of your Linked List class methods to better understand how they work and to review each method.

**Comment by PhraxayaM** [comment]
Thank you Faith!!
