### ISSUE TITLE
Feedback on Hash table

### ISSUE THREAD

**Issue by fchikwekwe** [PhraxayaM/CS-1.2-How-Data-Structures-Work#3]
Good work on this class so far.

You started to do time complexity analysis for some methods, but left it off for others. This is required in order to pass. Please also put _all_ of your time complexity annotations in the docstring to make sure that I don't miss the final analysis when reading your code. Please let me know when you've done this. 

(This next part isn't required) You've got a lot of random whitespace and large blocks of comments. You can enhance readability of your code a lot by removing code that you're not using anymore, moving comments to be next to their corresponding lines of code and removing any extraneous whitespace. Please message me if you need help refactoring this.

**Comment by PhraxayaM** [comment]
Okay I have updated it and I should be good to go. I will enhance the readability of my code per your instructions in my next update. I would like to save them in a different location but I have to take some time to see what I want to actually keep in order for me to review. I will do it when I have some more free time.

Thanks a lot for the help Faith!!
